before_script:
  - export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64
  - java -version
  - ant -version
  - cd benchmarks
  - touch local.properties
  - echo "make=/usr/bin/make" >> local.properties
  - echo "build.failonerror=true" >> local.properties
  - echo "jdk8home=/usr/lib/jvm/java-8-openjdk-amd64" >> local.properties
  - cat local.properties

cache:
  key: anu-gitlab-local
  untracked: true

biojava:
  script:
    - ant -Dbuild.target-jar=dacapo.jar biojava
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar biojava
  after_script:
    - git clean -df -e "downloads"

avrora:
  script:
    - ant -Dbuild.target-jar=dacapo.jar avrora
    - java -version
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar avrora
  after_script:
    - git clean -df -e "downloads"

batik:
  script:
    - ant -Dbuild.target-jar=dacapo.jar batik
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar batik
  after_script:
    - git clean -df -e "downloads"

cassandra:
  script:
    - ant -Dbuild.target-jar=dacapo.jar cassandra
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar cassandra
  after_script:
    - git clean -df -e "downloads"

eclipse:
  script:
    - ant -Dbuild.target-jar=dacapo.jar eclipse
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar eclipse
  after_script:
    - git clean -df -e "downloads"

fop:
  script:
    - ant -Dbuild.target-jar=dacapo.jar fop
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar fop
  after_script:
    - git clean -df -e "downloads"

graphchi:
  script:
    - ant -Dbuild.target-jar=dacapo.jar graphchi
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar graphchi
  after_script:
    - git clean -df -e "downloads"

h2:
  script:
    - ant -Dbuild.target-jar=dacapo.jar h2
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar h2
  after_script:
    - git clean -df -e "downloads"

jython:
  script:
    - ant -Dbuild.target-jar=dacapo.jar jython
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar jython
  after_script:
    - git clean -df -e "downloads"

luindex:
  script:
    - ant -Dbuild.target-jar=dacapo.jar luindex
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar luindex
  after_script:
    - git clean -df -e "downloads" -e "enwiki.txt"

lusearch:
  script:
    - ant -Dbuild.target-jar=dacapo.jar lusearch
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar lusearch
  after_script:
    - git clean -df -e "downloads"

pmd:
  script:
    - ant -Dbuild.target-jar=dacapo.jar pmd
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar pmd
  after_script:
    - git clean -df -e "downloads"

sunflow:
  script:
    - ant -Dbuild.target-jar=dacapo.jar sunflow
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar sunflow
  after_script:
    - git clean -df -e "downloads"

tomcat:
  script:
    - ant -Dbuild.target-jar=dacapo.jar tomcat
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar tomcat
  after_script:
    - git clean -df -e "downloads"
    - git clean -df -e "downloads"

tradebeans:
  script:
    - script -q -c "ant -Dbuild.target-jar=dacapo.jar tradebeans" script.out
    - sleep 120 | script -q -c "/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar tradebeans -s small" script.out
  after_script:
    - git clean -df -e "downloads"
    - git clean -df -e "downloads"

tradesoap:
  script:
    - script -q -c "ant -Dbuild.target-jar=dacapo.jar tradesoap" script.out
    - sleep 120 | script -q -c "/usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar tradesoap -s small" script.out
  after_script:
    - git clean -df -e "downloads"
    - git clean -df -e "downloads"

xalan:
  script:
    - ant -Dbuild.target-jar=dacapo.jar xalan
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar xalan
  after_script:
    - git clean -df -e "downloads"

zxing:
  script:
    - ant -Dbuild.target-jar=dacapo.jar zxing
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar zxing
  after_script:
    - git clean -df -e "downloads"

kafka:
  script:
    - ant -Dbuild.target-jar=dacapo.jar kafka
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar kafka
  after_script:
    - git clean -df -e "downloads"

jme:
  script:
    - ant -Dbuild.target-jar=dacapo.jar jme
    - /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar dacapo.jar jme
  after_script:
    - git clean -df -e "downloads"
